#!/bin/sh

# Disguise Safari on OS X as Mobile Safari on iPad/iPhone. 
# YouTube, Vimeo, etc will then send you H.264/MP4 video by default. 
# Also most iPad-optimized interfaces will be served instead. 
# Kinda neat. 



IPAD='"Mozilla/5.0 (iPad; U; CPU OS 3_2_2 like Mac OS X; en-us) AppleWebKit/531.21.10 (KHTML, like Gecko) Version/4.0.4 Mobile/7B500 Safari/531.21.10"'
IPHONE='"Mozilla/5.0 (iPhone; U; CPU iPhone OS 4_0_2 like Mac OS X; en-us) AppleWebKit/532.9 (KHTML, like Gecko) Version/4.0.5 Mobile/8A400 Safari/6531.22.7"'
IPAD_IOS5='"Mozilla/5.0 (iPad; CPU OS 5_0 like Mac OS X) AppleWebKit/534.46 (KHTML, like Gecko) Version/5.1 Mobile/9A334 Safari/7534.48.3"'

target=$1
case $target in
    ipad)       defaults write com.apple.Safari CustomUserAgent "$IPAD_IOS5";;       # fake iPad
    iphone)     defaults write com.apple.Safari CustomUserAgent "$IPHONE";;     # fake iPhone
    default)    defatuls delete com.apple.Safari CustomUserAgent;;              # revert to default
    *)          echo "Usage: fake-safari [default|ipad|iphone]";;
esac
